export const dataMenus = [
    {
        title: 'Comida',
        image: 'https://firebasestorage.googleapis.com/v0/b/almatierra-7796b.appspot.com/o/menu-comida.png?alt=media&token=e5d5e7b4-4b6f-4c7f-8b03-3d3bd9a029a7',
        banner: 'https://firebasestorage.googleapis.com/v0/b/almatierra-7796b.appspot.com/o/Bannercomida.jpg?alt=media&token=3905e73a-79af-44df-acbd-841c79e08c5c',
        categories: ['Entradas', 'Ensaladas y Sopas', 'Para compartir', 'Platos Fuertes', 'Postres']
    },
    {
        title: 'Desayunos',
        image:
            'https://firebasestorage.googleapis.com/v0/b/almatierra-7796b.appspot.com/o/menu-desayuno.jpg?alt=media&token=847a0b60-adb5-4b2c-94ed-1e150e1c2af5',
        categories: ['Para Despertar', 'Para compartir', 'Omelets', 'Chilaquiles', 'Lo Dulce']
    },
    {
        title: 'Bebidas',
        image:
            'https://firebasestorage.googleapis.com/v0/b/almatierra-7796b.appspot.com/o/menu-bebidas.jpg?alt=media&token=a493056d-e2c8-42be-b1a9-00558dc91b9b',
        categories: ['Bebidas Sin Alcohol']
    },
    {
        title: 'Cafetería',
        image:
            'https://firebasestorage.googleapis.com/v0/b/almatierra-7796b.appspot.com/o/menu-cafeteria.jpg?alt=media&token=22a2faaf-b4c5-4c6f-a15d-99a778627b15',
        categories: ['Café', 'Té', 'Tizanas']
    },
    {
        title: 'Mixología',
        image:
            'https://firebasestorage.googleapis.com/v0/b/almatierra-7796b.appspot.com/o/menu-mixologia.jpg?alt=media&token=4e8de5c6-d94e-4dc2-8599-6deac123c09a',

        categories: ['Mixología De La Casa', 'Coctelería Clásica', 'Licores Fuertes']
    },
    {
        title: 'Vinos',
        image:
            'https://firebasestorage.googleapis.com/v0/b/almatierra-7796b.appspot.com/o/menu-vinos.jpg?alt=media&token=30d86298-2073-46b1-ac7d-193b31471f2f',
        categories: ['Premium', 'Reserva', 'Crianza', 'Blancos', 'Rosados']
    },
]
export const imageCymbals = [
    { menu: 'Comida', categorie: 'Entradas', image: 'https://firebasestorage.googleapis.com/v0/b/almatierra-7796b.appspot.com/o/entrada1.jpg?alt=media&token=4e3cdfa1-7441-4856-a269-b773cf8400dd' },
    { menu: 'Comida', categorie: 'Entradas', image: 'https://firebasestorage.googleapis.com/v0/b/almatierra-7796b.appspot.com/o/entrada2.jpg?alt=media&token=a4bfd30e-efa1-471f-9ec3-d556cc02b6ed' },
    { menu: 'Comida', categorie: 'Entradas', image: 'https://firebasestorage.googleapis.com/v0/b/almatierra-7796b.appspot.com/o/entrada3.jpg?alt=media&token=02b98d98-7d80-4eb0-be43-3674a12716f1' },
    { menu: 'Comida', categorie: 'Entradas', image: 'https://firebasestorage.googleapis.com/v0/b/almatierra-7796b.appspot.com/o/entrada2.jpg?alt=media&token=a4bfd30e-efa1-471f-9ec3-d556cc02b6ed' },
    { menu: 'Comida', categorie: 'Entradas', image: 'https://firebasestorage.googleapis.com/v0/b/almatierra-7796b.appspot.com/o/entrada2.jpg?alt=media&token=a4bfd30e-efa1-471f-9ec3-d556cc02b6ed' },
]

export const dataCymbals = [
    { menu: 'Comida', categorie: 'Entradas', name: 'Crudo de atun', price: '310', description: 'Con recado negro y miso' },
    { menu: 'Comida', categorie: 'Entradas', name: 'Callo de aguachile', price: '375', description: 'Aguachile rojo de chiles oaxaqueños fermentados y mayonesa de ostion' },
    { menu: 'Comida', categorie: 'Entradas', name: 'Tiradito de pescado', price: '250', description: 'Pepino,cebolla morada, salsa verde de salicornia y mayonesa california' },
    { menu: 'Comida', categorie: 'Entradas', name: 'Jaiba de concha suave', price: '320', description: 'En salsa thermidor,jaiba frita,chocrut y chetextle' },
    { menu: 'Comida', categorie: 'Entradas', name: 'Tuetanos al grill', price: '350', description: 'Cebolla curtida y aguacate' },
    { menu: 'Comida', categorie: 'Entradas', name: 'Tlacoyos de pulpo y camaron', price: '280', description: 'Pulpo y camaron al ajillo' },
    { menu: 'Comida', categorie: 'Entradas', name: 'Bao de pato en salsa agridulce', price: '250', description: 'Salsa agridulce de chile ancho,pepino y cilantro' },
    { menu: 'Comida', categorie: 'Ensaladas y sopas', name: 'Ensalada betabel', price: '220', description: 'Burrata,betabel,fresa,tomate,nuez y vinagreta de frambuesa' },
    { menu: 'Comida', categorie: 'Ensaladas y sopas', name: 'Ensalada verde', price: '160', description: 'Manzana,uva,pepino,piñon y vinagreta de limon con miel' },
    { menu: 'Comida', categorie: 'Ensaladas y sopas', name: 'Sopa de hongos', price: '180', description: 'Amaranto,guajillo y epazote' },
    { menu: 'Comida', categorie: 'Ensaladas y sopas', name: 'Bisque de camaron', price: '240', description: 'Sofrito de pimientos con chile pasilla mize' },
    { menu: 'Comida', categorie: 'Ensaladas y sopas', name: 'Crema de tomate', price: '170', description: 'Sazonada con chicharron de cerdo' },
    { menu: 'Comida', categorie: 'Para compartir', name: 'Tabla de quesos', price: '395', description: 'Quesos de la region, aceitunas,charcuteria y pan de la casa' },
    { menu: 'Comida', categorie: 'Para compartir', name: 'Pezcado Zarandeado', price: '1250', description: 'A las brazas, ensalada y vegetales' },
    { menu: 'Comida', categorie: 'Para compartir', name: 'Tomahawk', price: '2200', description: 'Aligot y vegetales' },
    { menu: 'Comida', categorie: 'Para compartir', name: 'Lengua de res', price: '440', description: 'Salsa verde para taquear' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Pesca del dia ', price: '420', description: 'Gremolata de algas y emulsion de chiles' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Pulpo adobado', price: '450', description: 'Adobado con achiote y miso,esferas de papa, pure de zanahoria' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Cola de langosta', price: '720', description: 'Con risotto de salsa de langosta' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Colifor rostizada', price: '250', description: 'Aceite de chintextle, pipian de brocoli, chayote curtido, cremoso de pistache' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Magret de pato', price: '365', description: 'Termino medio,mole negro y betabel' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Pollito lechal asado', price: '390', description: 'Pure de camate, garbanzos, alubias , quinoa y vinagreta de chicatana' },
    { menu: 'Comida', categorie: 'Platos Ffuertes', name: 'Lechon confitado', price: '425', description: 'Mole encacahuatado y vegetales en escabeche' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'Chamorro de borrego', price: '690', description: 'Braseado con pure de coliflor' },
    { menu: 'Comida', categorie: 'Platos Fuertes', name: 'New York', price: '890', description: 'Al grill con aligot y vegetales' },
    { menu: 'Comida', categorie: 'Postres', name: 'Selva negra', price: '220', description: 'Mouse de chocolate, cujriente de cacao y cumbre de brownie' },
    { menu: 'Comida', categorie: 'Postres', name: 'Limon real', price: '180', description: 'Limon confitado, ganache de limon  y cumbre de mantequilla' },
    { menu: 'Comida', categorie: 'Postres', name: 'Tarta rustica', price: '180', description: 'Galette de fruta de temporada' },
    { menu: 'Comida', categorie: 'Postres', name: 'Baklava', price: '180', description: 'Pasta fillo , nuez, canela y mantequilla' },
    { menu: 'Comida', categorie: 'Postres', name: 'Cafe lechero', price: '175', description: 'Panna cotta de leche y jarabe de cafe veracruzano' },
    { menu: 'Desayunos', categorie: 'Para despertar', name: 'Bowl de fruta con yogurt', price: '115', description: 'yogurt de frutas , frutas de temporada, granola y miel de abeja' },
    { menu: 'Desayunos', categorie: 'Para despertar', name: 'Plato de frutas con ricotta', price: '145', description: 'Queso ricotta, fruta de temporada y nuez caramelizada' },
    { menu: 'Desayunos', categorie: 'Para despertar', name: 'Avocado Toast', price: '125', description: 'Pan de masa madre, aguacate , tomate y huevo pochado' },
    { menu: 'Desayunos', categorie: 'Para Compartir', name: 'Borrego tatemado', price: '270', description: 'Orden de borrego tatemado,frijoles,queso fresco y tortillas' },
    { menu: 'Desayunos', categorie: 'Para despertar', name: 'Shakshuka', price: '200', description: 'Vegetales salteados en salsa de tomado,aceite de oliva y especias, huevos estrellados y queso de cabra ' },
    { menu: 'Desayunos', categorie: 'Omelets', name: 'A la mexicana', price: '270', description: 'Cebolla,tomate, chile california, queso y salsa de frijol' },
    { menu: 'Desayunos', categorie: 'Omelets', name: 'Hongos', price: '220', description: 'Bañado en salsa de quesos, champiñones confitados , esparragos y tomate' },
    { menu: 'Desayunos', categorie: 'Omelets', name: 'Camaron', price: '280', description: 'Sofrito de camaron con tocino y queso, ensalada y aguacate' },
    { menu: 'Desayunos', categorie: 'Omelets', name: 'Costilla', price: '240', description: 'Salsa roja , costilla de res braseada, queso y frijoles' },
    { menu: 'Desayunos', categorie: 'Chilaquiles', name: 'Rojos', price: '140', description: 'Salsa roja, queso cotija, cebolla y huevo al gusto con frijoles' },
    { menu: 'Desayunos', categorie: 'Chilaquiles', name: 'Hongos', price: '140', description: 'Salsa roja, queso cotija, cebolla y huevo al gusto con frijoles' },
    { menu: 'Desayunos', categorie: 'Chilaquiles', name: 'Camaron', price: '140', description: 'SSalsa roja, queso cotija, cebolla y huevo al gusto con frijoles' },
    { menu: 'Desayunos', categorie: 'Lo Dulce', name: 'Wafles', price: '210', description: 'Salsa toffe, helado espresso y fruta' },
    { menu: 'Desayunos', categorie: 'Lo Dulce', name: 'Pan fancres', price: '110', description: 'Wafle , miel , almendra y fruta' },
    { menu: 'Desayunos', categorie: 'Lo Dulce', name: 'Canasta de pan', price: '110', description: 'Pan dulce hecho en casa' },
    { menu: 'Desayunos', categorie: 'Bebidas Sin Alcohol', name: 'Piñada', price: '120', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Limonada natural', price: '45', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Limonada mineral', price: '45', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Naranjada', price: '120', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Cocacola', price: '120', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Sprite', price: '120', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Piñada', price: '120', description: '' },
    { menu: 'Bebidas', categorie: 'Bebidas Sin Alcohol', name: 'Piñada', price: '120', description: '' },
    { menu: 'Cafeteria', categorie: 'Cafe', name: 'Espresso', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Cafe', name: 'Cafe americano', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Cafe', name: 'Latte', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Cafe', name: 'Capuccino', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Cafe', name: 'Mocha', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Negro', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Verde', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Manzanilla', price: '50', description: '' },
    { menu: 'Desayunos', categorie: 'Té', name: 'Jazmin', price: '50', description: '' },
    { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'Carajillo', price: '210', description: 'Licor 43, cerveza artesanal y espresso' },
    { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'La chingadera', price: '210', description: 'Jarabe de gengibre, agua tonica y cocacola' },
    { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'La chingadera', price: '210', description: 'Jarabe de gengibre, agua tonica y cocacola' },
    { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'La chingadera', price: '210', description: 'Jarabe de gengibre, agua tonica y cocacola' }, { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'La chingadera', price: '210', description: 'Jarabe de gengibre, agua tonica y cocacola' }, { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'La chingadera', price: '210', description: 'Jarabe de gengibre, agua tonica y cocacola' }, { menu: 'Mixologia', categorie: 'Mixologia de la casa', name: 'La chingadera', price: '210', description: 'Jarabe de gengibre, agua tonica y cocacola' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Coctelería Clásica', name: 'Abe', price: '190', description: '' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', price: '2700', description: 'shot:160' },
    { menu: 'Mixologia', categorie: 'Licores Fuertes', name: '1800', price: '2700', description: 'shot:160' },
    { menu: 'Vino', categorie: 'Premium', name: 'Negro', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Verde', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Manzanilla', price: '50', description: '' },
    { menu: 'Desayunos', categorie: 'Té', name: 'Jazmin', price: '50', description: '' },
    { menu: 'Vino', categorie: 'Premium', name: 'Negro', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Verde', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Manzanilla', price: '50', description: '' },
    { menu: 'Desayunos', categorie: 'Té', name: 'Jazmin', price: '50', description: '' },
    { menu: 'Vino', categorie: 'Premium', name: 'Negro', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Verde', price: '50', description: '' },
    { menu: 'Cafeteria', categorie: 'Té', name: 'Manzanilla', price: '50', description: '' },
    { menu: 'Desayunos', categorie: 'Té', name: 'Jazmin', price: '50', description: '' },
]